# Generated by Django 2.0.4 on 2018-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ringsize', models.CharField(max_length=256)),
                ('ringindex', models.CharField(max_length=256)),
                ('block', models.CharField(max_length=256)),
                ('timestamp', models.CharField(max_length=256)),
                ('chain', models.CharField(max_length=256)),
                ('ringhash', models.CharField(max_length=256)),
                ('mineraddress', models.CharField(max_length=256)),
                ('order1hash', models.CharField(max_length=256)),
                ('order1amount', models.CharField(max_length=256)),
                ('order1nextamount', models.CharField(max_length=256)),
                ('order1lrcReward', models.CharField(max_length=256)),
                ('order1lrcFeeState', models.CharField(max_length=256)),
                ('order1splitS', models.CharField(max_length=256)),
                ('order1splitB', models.CharField(max_length=256)),
                ('order2hash', models.CharField(max_length=256)),
                ('order2amount', models.CharField(max_length=256)),
                ('order2nextamount', models.CharField(max_length=256)),
                ('order2lrcReward', models.CharField(max_length=256)),
                ('order2lrcFeeState', models.CharField(max_length=256)),
                ('order2splitS', models.CharField(max_length=256)),
                ('order2splitB', models.CharField(max_length=256)),
                ('order3hash', models.CharField(max_length=256)),
                ('order3amount', models.CharField(max_length=256)),
                ('order3nextamount', models.CharField(max_length=256)),
                ('order3lrcReward', models.CharField(max_length=256)),
                ('order3lrcFeeState', models.CharField(max_length=256)),
                ('order3splitS', models.CharField(max_length=256)),
                ('order3splitB', models.CharField(max_length=256)),
            ],
        ),
    ]
